Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 07/01/2023
Var
// Seção de Declarações das variáveis 

i, x, y : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

x <- 4
y <- x + 2

  para i de 1 ate x faca

       escreva (x, " ", y)
       y <- y + i

  fimpara

Fimalgoritmo